# Generated by Django 2.1.4 on 2018-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='svg',
            field=models.TextField(blank=True),
        ),
    ]
