# Generated by Django 2.1.4 on 2018-12-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='plants',
            field=models.ManyToManyField(blank=True, null=True, to='plants.Plant'),
        ),
    ]
