# Generated by Django 2.1.4 on 2018-12-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField(null=True)),
                ('y', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveSmallIntegerField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.Bed')),
            ],
        ),
        migrations.CreateModel(
            name='PlantSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('web_address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('latin_name', models.CharField(blank=True, max_length=128, null=True)),
                ('full_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('full_diameter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('light', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Full shade'), (2, 'Partial shade'), (3, 'Shade tolerant'), (4, 'Partial sun'), (5, 'Full sun')], null=True)),
                ('water', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('annual', models.BooleanField(default=False)),
                ('companions', models.ManyToManyField(related_name='_plantspecies_companions_+', to='plants.PlantSpecies')),
                ('harvest', models.ManyToManyField(related_name='plants_to_harvest', to='planner.Month')),
                ('plant_out', models.ManyToManyField(related_name='plants_to_plant_out', to='planner.Month')),
                ('seed_indoors', models.ManyToManyField(related_name='plants_to_seed_indoors', to='planner.Month')),
                ('seed_outdoors', models.ManyToManyField(related_name='plants_to_seed_outdoors', to='planner.Month')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.PlantSource'),
        ),
        migrations.AddField(
            model_name='plant',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.PlantSpecies'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='plants',
            field=models.ManyToManyField(to='plants.Plant'),
        ),
    ]
