# Generated by Django 2.1.4 on 2018-12-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantspecies',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_species', to='auth.Group'),
        ),
    ]
