# Generated by Django 2.1.4 on 2018-12-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['id']},
        ),
    ]
